### ISSUE TITLE
No IFR data found with new UEFI 2.8 AMI bios

### ISSUE THREAD

**Issue by longnt2007** [LongSoft/IFRExtractor-RS#21]
Hello,
I've tried dump my bios and extract Setup from dumped bios with UEFITool (click on PE32 image section and select Extract as is...)
![uefi](https://github.com/LongSoft/IFRExtractor-RS/assets/16752180/af15a614-c63c-4ea5-8eb0-84a16fa748f4)

After that, I run command IFRExtractor but it said no IFR data found.
![error](https://github.com/LongSoft/IFRExtractor-RS/assets/16752180/22312bbc-0330-4164-9ff5-efd6f7129f8b)

Here is the Setup file.
[Section_PE32_image_Setup_Setup.zip](https://github.com/LongSoft/IFRExtractor-RS/files/14473025/Section_PE32_image_Setup_Setup.zip)

Could you check if there is any error with this Setup file ?

**Comment by lvu249909001** [comment]
Actually ifrextractor doesn't recognize IFR data from new Raptor Lake 13th platform (especially bios from Asus manufacturer from version 3.00 onward). Either Alder Lake 12th platform or Meteor Lake platform is fine.
