### ISSUE TITLE
Differing Sizes from IFRExtractor LS and RS

### ISSUE THREAD

**Issue by adelinadragonborn** [LongSoft/IFRExtractor-RS#23]
Hi! I've just found that RS shows Size: 8 on some variables which has a few options of values (for example Disabled or Enabled), while LS shows Size: 1 as expected. Is this because of RS reports Size as bits and LS as bytes?

I'm asking because some tools like setup_var.efi uses bytes (as param) to write values, and may be confusing for someone who wants to use this tool.

A documentation or difference list between LS and RS would be appreciated.

Thanks in advance.

**Comment by BoringBoredom** [comment]
> Is this because of RS reports Size as bits and LS as bytes?

yes

**Comment by NikolajSchlej** [comment]
LS is an outdated for of an outdated tool that is a miracle to still work in 2024. The only documentation required is "please don't use LS, RS is a supported replacement".
