### ISSUE TITLE
Support Framework HII tables

### ISSUE THREAD

**Issue by vit9696** [LongSoft/IFRExtractor-RS#6]
Can be found in APTIO IV firmware (e.g. Haswell). Example: https://dlcdnets.asus.com/pub/ASUS/mb/LGA1150/Z87-PRO/Z87-PRO-ASUS-2103.zip

**Comment by Falcosc** [comment]
What information can not be extracted as long as we don't have this improvement?

Could we still find out which PCIe Bifurcation options are available for Boards like LGA1150? Or are Framework HII tables requires to parse it?

**Comment by NikolajSchlej** [comment]
Framework HII tables are only applicable to fairly old motherboards of Aptio4 era (SandyBridge, IvyBridge, Hasswell and alike). Only those aren't supported by IFRExtractor-RS yet, all newer stuff is already fine.

**Comment by Falcosc** [comment]
So you can not parse anything from Aptio4 boards.
Is any 1155 and 1150 board and older effected? Or are there some LGA1155 exceptions which don't use Aptio4?

**Comment by NikolajSchlej** [comment]
HII tables is what gets parsed by IFR extractors, they have both the strings (text) and the forms (structures and offsets).
None of the 1155 or 1150 boards are affected, AFAIK.

**Comment by Falcosc** [comment]
> None of the 1155 or 1150 boards are affected, AFAIK.

SandyBridge, IvyBridge, Hasswell are LGA1155 and LGA1150. So you mean all of the 1155 or 1150 boards are affected, instead of None, or where did I misunderstand where the support of the new tool ends?

I will write it into the README since releases of Universal-IFR-Extractor are 2 years more recent you would never guess that IFRExtractor-RS is the tool to use.

**Comment by NikolajSchlej** [comment]
Let me just correct that Framework HII issue in IFRExtractor and move on from figuring out what is supported and what is not.
As for releases, there's an upcoming one.

**Comment by NikolajSchlej** [comment]
Turns out the sample @vit9696 provided used UEFI structures after all, but this one is certainly using Framework HII
[BL0163.bio.zip](https://github.com/LongSoft/IFRExtractor-RS/files/9889143/BL0163.bio.zip)

**Comment by NikolajSchlej** [comment]
Resolved by https://github.com/LongSoft/IFRExtractor-RS/commit/45c9b729c36908e77e5aa6876790410c17b3fb03
