### ISSUE TITLE
Collect images to test that every opcode is getting parsed correctly

### ISSUE THREAD

**Issue by NikolajSchlej** [LongSoft/IFRExtractor-RS#9]
There are a lot (100+) of small parsers for both Framework and UEFI HII structures, and there are also a ton of images out there in the wild.
We need to ensure that every opcode that is possible in a firmware image is indeed parsed correctly, and if not, fix it.

- [x] Investigate UEFI VarStoreEfi opcode not getting parsed on some images
- [x] Build a collection of images covering as many UEFI and Framework opcodes as possible, probably with help of LVFS project (CC @hughsie)

**Comment by hughsie** [comment]
Happy to help; yell if you want me to run a script on my local mirror of firmware.

**Comment by NikolajSchlej** [comment]
Please do something like this:
```
for current_image in the_collection {
   UEFIExtract current_image
   for file_named_body.bin in current_image.dump/ {
      IFRExtractor body.bin > output.txt
      // It will also generate one or more body.bin.*.ifr.txt files

      for file in files_named_"output.txt" {
          rename file unique_file_name.output.txt
          archive add unique_file_name.output.txt outputs.archive
      }

      for file in files_named_"*.ifr.txt" {
          rename file unique_file_name.ifr.txt
          archive add unique_file_name.ifr.txt ifrs.archive
      }

      remove current_image.dump
   } 
}

upload ifrs.archive outputs.archive
```

Can take forever hours and a half, but will help tremendously in improving this tool.

**Comment by NikolajSchlej** [comment]
I can write this into a proper shell script, if needed, but IDK what archiver do you have on your server and what is the format of ```find``` command your OS uses.

**Comment by hughsie** [comment]
> what archiver do you have on your server

Linux, Fedora 37. I'm tempted to just dump this in the UEFITool plugin on the LVFS, so python preferred.

**Comment by NikolajSchlej** [comment]
CC @matrosov, who might also be interested in ifrs.archive.

Ok, Python it is.

**Comment by NikolajSchlej** [comment]
@hughsie, attaching the script, it takes a single ```-i /path/to/input_file.bin``` argument and generates a ```/path/to/input_file.bin.ifrs.zip``` archive if everything goes as planned. 
License: BSD 2-Clause.
[extract_ifrs.py.zip](https://github.com/LongSoft/IFRExtractor-RS/files/9954553/extract_ifrs.py.zip)

**Comment by NikolajSchlej** [comment]
Updated the tool to support verbose mode, please replace 
```
# Run IFRExtractor on the file
result_IFRE = subprocess.run([ifrextractor_path, path], stdout=subprocess.PIPE)
```
with 
```
# Run IFRExtractor on the file
result_IFRE = subprocess.run([ifrextractor_path, path, 'verbose'], stdout=subprocess.PIPE)
```
Will get a better output this way.

**Comment by NikolajSchlej** [comment]
Binaries for the current top of tree can be downloaded from this page (scroll to the bottom): https://github.com/LongSoft/IFRExtractor-RS/actions/runs/3413889149

**Comment by NikolajSchlej** [comment]
Truncated VarStoreEfi sample
[Section_PE32_image_CFEF94C4-4167-466A-8893-8779459DFA86_PlatformSetupAdvancedDxe.efi_body.efi.zip](https://github.com/LongSoft/IFRExtractor-RS/files/9958673/Section_PE32_image_CFEF94C4-4167-466A-8893-8779459DFA86_PlatformSetupAdvancedDxe.efi_body.efi.zip)

**Comment by NikolajSchlej** [comment]
https://github.com/LongSoft/IFRExtractor-RS/releases/tag/v1.4.0

**Comment by NikolajSchlej** [comment]
@hughsie, got a chance to run that script above yet?
I'm now in full "let's prepare for the move to the US" mode, so I'll probably be out of the Internet for a while, might reply with significant delays.

**Comment by hughsie** [comment]
Hey, sorry; not yet. I've been dealing with fallout from that UEFI disclosure yesterday. Today hopefully.

**Comment by hughsie** [comment]
Script running, should be complete in about 5 hours (!)

**Comment by NikolajSchlej** [comment]
Done investigating that collection, no parsing issues found.
